[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "01afd2b22db63bdcaa6abf3684f3ac1cc012eece"
os = "macos"

    [[pagefind.download]]
    sha256 = "3097b82ac3dc0d7d3d78d242bfd68bc0753ab5432eed6712501b87f9c05c0716"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind-v1.1.0-aarch64-apple-darwin.tar.gz"
[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "0e13da26e20910a865764a2d062a84418279e445"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "fef38491d13817d85a1b05710c1de05840e4568617ca5bf0b0a1637ec2617e02"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind-v1.1.0-aarch64-unknown-linux-musl.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "bcd6b0e8d90b87f0ff4343a284c3beb465f837ea"
os = "macos"

    [[pagefind.download]]
    sha256 = "5ffd34d32addc2454b436cfbb4894b6220e60d97f32ed003a95db9b1903ad2a0"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind-v1.1.0-x86_64-apple-darwin.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "c67f9bb17c92f6760787f4c4479eb2503d5966e7"
os = "windows"

    [[pagefind.download]]
    sha256 = "a04a99318d3604343a3c99c86bcf8c35e829ff7f729a4ec1b6d66adfaaf52e6f"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind-v1.1.0-x86_64-pc-windows-msvc.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "6f47be3510b9737d61bdf584a2ba1bcfdf75885d"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "b20d0b06b54eb2fba1e290245919376364584a456fb644e66eecdb67549b1cf2"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind-v1.1.0-x86_64-unknown-linux-musl.tar.gz"

[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "158549b9490d6c407a7fabaf4a1ccb02a294b388"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "e33ee297b885abcce4a674b70779778e354d7ae4eb1a0b7b15dea48852d80cb7"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-aarch64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "ff70ace3f8ca491431661b4feaf5406467617b4a"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "b05661d856372beea75468ea683f197b465e019f033259768f65988c9598f390"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-aarch64-unknown-linux-musl.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "0834286c7a1cb75105ce0d9fee11ee18dfad465d"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "907d526d1d40de7a15060a495a460d00ed461fa6e6963278d90152360ea24346"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-x86_64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "67fba7bead8fd1052bac994ea232a821eb859404"
lazy = true
os = "windows"

    [[pagefind_extended.download]]
    sha256 = "5c534b4d69bcae15e3684e074150eefa1b9b16d5f359e10f349bc5add6af5ea6"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-x86_64-pc-windows-msvc.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "07e95ea924aaba04bb273d54745a11f155f7b07e"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "583cf2753fb2070448a9c9cf1f31acd1b96af99b9ca0a450faf9bb376420bac4"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.1.0/pagefind_extended-v1.1.0-x86_64-unknown-linux-musl.tar.gz"
