[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "208208ad126268a209f0d9f213270f2d471ca002"
os = "macos"

    [[pagefind.download]]
    sha256 = "539967411d4d3a8b6a47841906d9a632eb4f419ffed01a2301d48c9b9b394d60"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind-v1.3.0-aarch64-apple-darwin.tar.gz"
[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "bb7fd115565ab0c607a31e9427d9e637783bb608"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "0662a9b81a5b40112fc0d99a5aec8a3ac1fcdd7b396bee605f1fbd37c11bc427"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind-v1.3.0-aarch64-unknown-linux-musl.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "e90175ae83a524a37a4d55f9eabb2de78435c2a4"
os = "macos"

    [[pagefind.download]]
    sha256 = "ea716b8a1cf8d8b81a18c331f011af19916f30374b15f0fd88d90469bcbf5da9"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind-v1.3.0-x86_64-apple-darwin.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "08af5ddbbc03775deaabc767c35d5e90f1484ea4"
os = "windows"

    [[pagefind.download]]
    sha256 = "ed949ae695e6558e8c73fbbb9e650e1000b9d534e76ca9bf970ae4f55057b227"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind-v1.3.0-x86_64-pc-windows-msvc.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "7da9c228b743001302159ae9667ea52998a09089"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "5dfb56609c2d08058c3be56a1a2d332d8dc50d9a6c74f20b3619eadb53240af3"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind-v1.3.0-x86_64-unknown-linux-musl.tar.gz"

[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "1989c57f5cfa0dba9459224aedfa51638fd0c5b1"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "3ba48fde09150c0332b06b30f3b214f0838e031563b27aad78cf6a46ac434bcc"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind_extended-v1.3.0-aarch64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "e7edd48cc82eb3c93235ac40294f36a4ae93dc35"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "21294be42afd75818f3c38b26ec69ee3fa68a98f2396e412c1ebb72727b4c526"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind_extended-v1.3.0-aarch64-unknown-linux-musl.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "ce54b3df946c2267942eddc7f6b366c74e4f7e3a"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "b9a604c79a3d00c21c6f505aa22eff164b0c28e64b91d3c0fda0fcfceff7ac79"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind_extended-v1.3.0-x86_64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "d082d2a2156f8519dcdd38403c9aa0fcf8150975"
lazy = true
os = "windows"

    [[pagefind_extended.download]]
    sha256 = "6543e83c694f75f3fdc5b278ce2d13bae14e4d2525cb42cc0eadc1fbc72e649a"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind_extended-v1.3.0-x86_64-pc-windows-msvc.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "bc6f474173e1fd6cfd0998fcfea4a7d00de80d4e"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "f983dec5507d87c7c497c450d2c5de97fc967a46d26e0ac3fb7184a87c94e434"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.3.0/pagefind_extended-v1.3.0-x86_64-unknown-linux-musl.tar.gz"
