[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "a2c1a49ddd4a80e3b7e8ba773f4290e9da247971"
os = "macos"

    [[pagefind.download]]
    sha256 = "46aad86224775e20b7e60b39878d0c027dd3b21e5e4db972cdf83bc909e33f87"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind-v1.0.3-aarch64-apple-darwin.tar.gz"
[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "2b26c37be760144e56e92d9adafe75234bbf63f8"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "321ef7e79d6e8199c92b9d3fc96aed5d52fd25e6547a0eb0199eaac88846b959"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind-v1.0.3-aarch64-unknown-linux-musl.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "f5f9ba605f710b1cc98471bf73eec2b351e517c4"
os = "macos"

    [[pagefind.download]]
    sha256 = "24a416bbddec9a31fc6eda974b4ef0d1efcabbed77752861f022669f5bc594c5"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind-v1.0.3-x86_64-apple-darwin.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "2ccc0e1329a3b4ffac2f920e3def0a4606d97323"
os = "windows"

    [[pagefind.download]]
    sha256 = "02d34e8439764a062f3cc864d4d98afe4853db0828ae5f6475487f923c295441"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind-v1.0.3-x86_64-pc-windows-msvc.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "d6d95a9f7c8f58e260351e1f53c9592e874e8950"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "e84ec7e8cb424022aa70ca14e6735c67c9728596753321dec782a902c3bfe6f0"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind-v1.0.3-x86_64-unknown-linux-musl.tar.gz"

[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "c6b6f632b3c619adc8baed2cdc79d93333bc2e52"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "a6fa3fafd463d00ecccb210d2378d9d3886b99b87938af0ebf7924365e50d721"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind_extended-v1.0.3-aarch64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "27313057aba7c2b2a40f270de6c3aefb51476936"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "575885fb7086a31b9322b7bba0b0baf57bb2586b1fcc7661a88a73ffe17c8134"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind_extended-v1.0.3-aarch64-unknown-linux-musl.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "222dfa5adcfcbfc27c540f58ca8fe0065d538394"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "25cb3c52431bebd7eeec61b611aab546efe6a23cca859ab64e73a85692f8642e"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind_extended-v1.0.3-x86_64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "dc94f75c7e97b46c8f5f8af3202a40a1b9340d1e"
lazy = true
os = "windows"

    [[pagefind_extended.download]]
    sha256 = "1df089cf6cc892e9296a5aa2701639097856598508cab0cd94b3336ea0335c47"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind_extended-v1.0.3-x86_64-pc-windows-msvc.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "d59ccca0b99bf42bd6d9fbb2c0e918b533563e53"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "aec60f1db9fd693986b2c3d6253f98e6710e5046a371fc1c7e3ecc5fc982a95d"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.3/pagefind_extended-v1.0.3-x86_64-unknown-linux-musl.tar.gz"
