[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "7fbda8c81ce31749a2b2520a5dd9c5221a64584b"
os = "macos"

    [[pagefind.download]]
    sha256 = "f37101bc4986606b48c5fd4c99f04c413efabbae1fd0913c3bbb3b341c426787"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind-v1.0.4-aarch64-apple-darwin.tar.gz"
[[pagefind]]
arch = "aarch64"
git-tree-sha1 = "872af581293457bca8758867caa55fb8986b65da"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "df1b3311d6f2bf3c1d78a735ee83a00cb301d9fde658266ad4b5845ab2441eeb"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind-v1.0.4-aarch64-unknown-linux-musl.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "448621af0ed6b662ad56a4890b94f0156ba225d0"
os = "macos"

    [[pagefind.download]]
    sha256 = "18a456c3a7f06bd587f42c9911abe49db532a47268e45d4500955d89f050a0b2"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind-v1.0.4-x86_64-apple-darwin.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "02325ec46813eca2b53f51b6f1f37fdde5dac381"
os = "windows"

    [[pagefind.download]]
    sha256 = "4869ef223a923b6d5b54b31e861c855ba92dd7f18fe53510c3dc2b0a3ce198aa"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind-v1.0.4-x86_64-pc-windows-msvc.tar.gz"
[[pagefind]]
arch = "x86_64"
git-tree-sha1 = "54dd0171a25860e3182e69eeac5d88073150b60e"
libc = "glibc"
os = "linux"

    [[pagefind.download]]
    sha256 = "a3a1ecf1d6edd79551c8b98a863b20cbdd999316a6ca73e81e277a74449db886"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind-v1.0.4-x86_64-unknown-linux-musl.tar.gz"

[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "7b26f25a61ec29332758deda5e9610ed4d6d39d3"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "173ad49d20b818550f4ec49f2b860aa80cae3a5bd955d2bdcc2614c3b9faaa80"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind_extended-v1.0.4-aarch64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "aarch64"
git-tree-sha1 = "96f523e895054d4860e0be67e4fc66039140162f"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "f450a5bb1f372fbf140fa59bdd0fc424900b7317f67f82538286ccf90e6498de"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind_extended-v1.0.4-aarch64-unknown-linux-musl.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "740a43f7d12b0be675391b9927ad2361d55702a2"
lazy = true
os = "macos"

    [[pagefind_extended.download]]
    sha256 = "8737db007cf41aa14df488d01b01707f679fc6d3b899902c10d74a59a2916f2a"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind_extended-v1.0.4-x86_64-apple-darwin.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "5affa5033682ad8d967250daab1e714e2baf9558"
lazy = true
os = "windows"

    [[pagefind_extended.download]]
    sha256 = "38aeb0b359f3e408cf517c5554421a947addd8be126e51342a66864eaf0cdefb"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind_extended-v1.0.4-x86_64-pc-windows-msvc.tar.gz"
[[pagefind_extended]]
arch = "x86_64"
git-tree-sha1 = "7c31eb259f867c7b5151ea3212f09c715806171f"
lazy = true
libc = "glibc"
os = "linux"

    [[pagefind_extended.download]]
    sha256 = "61cdee630d3fbb30763a982ed0c895731d143d6c60a96c37f261aba4837cb930"
    url = "https://github.com/CloudCannon/pagefind/releases/download/v1.0.4/pagefind_extended-v1.0.4-x86_64-unknown-linux-musl.tar.gz"
