name = "PagefindWrapper"
uuid = "32f3d815-099f-4670-87cf-dd827b2a53b5"
authors = ["Michael Hatherly <michaelhatherly@gmail.com>"]
version = "1.0.1"

[deps]
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"

[compat]
LazyArtifacts = "1"
julia = "1.6"
